CREATE TABLE "FILE" (
	"ID" TEXT,
	"NAME" TEXT NOT NULL,
        "ABSOLUTE_PATH" TEXT NOT NULL,
        "LAST_MODIFICATION_DATE" TEXT NOT NULL,
        "LAST_CHECK_DATE" TEXT NOT NULL,
        "HASH_SUM_VALUE" TEXT NOT NULL,
        "HASH_SUM_ALGORITHM" TEXT NOT NULL,
        UNIQUE(ABSOLUTE_PATH),
	PRIMARY KEY("ID")
);

CREATE UNIQUE INDEX IDX_FILE_ABSOLUTE_PATH 
ON FILE (ABSOLUTE_PATH);